#!/usr/bin/env python3
"""Generate this repo's files from tools.json.

Usage:
  python3 scripts/build.py                               # write README.md, server.json, servers/<slug>/server.json
  python3 scripts/build.py --check-site path/to/site     # also compare with the website's /tools.json (read-only)

Writes only inside this repo. It never writes to the website. The site (plainfold.github.io: index.html,
llms.txt, llms-full.txt, tools.json, robots.txt, sitemap.xml) is generated by its own build from site-v2/src/data.py.
--check-site reads the site's tools.json and exits non-zero if tool status or prices differ from tools.json here.
To add a tool: add/complete its entry in tools.json, set "live": true, bump brand.combined.version, rerun.
"""
import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCHEMA = "https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json"
DATA = json.load(open(os.path.join(ROOT, "tools.json"), encoding="utf-8"))
B = DATA["brand"]
TOOLS = [t for t in DATA["tools"] if t.get("live")]
SOON = [t for t in DATA["tools"] if not t.get("live")]


def mcp_url(slugs):
    return "https://mcp.apify.com/?tools=" + ",".join("plainfold/" + s for s in slugs)


def apify_url(t):
    return "https://apify.com/plainfold/" + t["slug"]


def tool_name(t):  # name the Apify MCP server gives the tool
    return "plainfold--" + t["slug"]


def write(path, text):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


ALL_URL = mcp_url([t["slug"] for t in TOOLS])
AUTH_HEADER = {
    "name": "Authorization",
    "description": "Apify API token as 'Bearer <token>' (free account at apify.com). Optional if your MCP client supports OAuth sign-in.",
    "isRequired": False,
    "isSecret": True,
}
ICONS = [{"src": B["site"] + "/assets/plainfold-icon-512.png", "mimeType": "image/png", "sizes": ["512x512"]}]


def server_json(name, title, desc, version, url, website, subfolder=None):
    assert len(desc) <= 100, (name, len(desc))
    repo = {"url": B["repo"], "source": "github"}
    if B.get("repoId"):
        repo["id"] = str(B["repoId"])
    if subfolder:
        repo["subfolder"] = subfolder
    return {
        "$schema": SCHEMA,
        "name": name,
        "title": title,
        "description": desc,
        "version": version,
        "websiteUrl": website,
        "repository": repo,
        "icons": ICONS,
        "remotes": [{"type": "streamable-http", "url": url, "headers": [AUTH_HEADER]}],
    }


def build_servers():
    c = B["combined"]
    sj = server_json(f'{B["registryNamespace"]}/{c["slug"]}', c["title"], c["description"], c["version"], ALL_URL, B["site"])
    write(os.path.join(ROOT, "server.json"), json.dumps(sj, indent=2, ensure_ascii=False) + "\n")
    for t in TOOLS:
        sj = server_json(f'{B["registryNamespace"]}/{t["slug"]}', t["name"], t["registryDescription"], t["version"],
                         mcp_url([t["slug"]]), apify_url(t), subfolder=f'servers/{t["slug"]}')
        write(os.path.join(ROOT, "servers", t["slug"], "server.json"), json.dumps(sj, indent=2, ensure_ascii=False) + "\n")


def client_configs(key, url):
    cursor = {"mcpServers": {key: {"url": url, "headers": {"Authorization": "Bearer YOUR_APIFY_TOKEN"}}}}
    vscode = {"servers": {key: {"type": "http", "url": url}}}
    claude = {"mcpServers": {key: {"command": "npx", "args": ["-y", "mcp-remote", url, "--header", "Authorization:${AUTH_HEADER}"],
                                   "env": {"AUTH_HEADER": "Bearer YOUR_APIFY_TOKEN"}}}}
    return cursor, vscode, claude


def readme():
    L = []
    L.append('<p align="center"><img src="assets/plainfold-logo-light.png" alt="Plainfold" width="360"></p>\n')
    L.append("# Plainfold MCP tools\n")
    L.append(f'{B["tagline"]} Each tool runs on [Apify]({B["apifyProfile"]}) and is available to AI agents as a remote MCP server '
             "through Apify's hosted MCP endpoint. You pay per result, at the prices below. There's nothing to install or host.\n")
    L.append('[![Listed on mcpservers.org](https://mcpservers.org/badge.svg)](https://mcpservers.org/servers/plainfold/plainfold-mcp)\n')
    L.append(f'Website: {B["site"]} · Machine-readable index: {B["site"]}/llms.txt\n')
    L.append("## Tools\n")
    L.append("| Tool | What it does | Price | MCP URL |\n|---|---|---|---|")
    for t in TOOLS:
        L.append(f'| [{t["name"]}]({apify_url(t)}) | {t["summary"]} | {t["priceShort"]} | `{mcp_url([t["slug"]])}` |')
    L.append(f'\nAll tools in one server: `{ALL_URL}`\n')
    if SOON:
        L.append("Coming soon: " + "; ".join(f'{t["name"]} ({t["summary"].rstrip(".")})' for t in SOON) + ".\n")
    L.append("## Quick start\n")
    L.append("1. Get an Apify account (free) at https://apify.com. MCP clients that support OAuth (Claude, VS Code, Cursor) "
             "can sign in to Apify in the browser, so you don't need to copy a token. Otherwise, copy your API token from "
             "https://console.apify.com/account/integrations.\n2. Add one of the URLs above to your MCP client (examples below).\n"
             "3. Ask your agent a question. It calls the tool, and the run is billed to your Apify account at the tool's price.\n")
    cursor, vscode, claude = client_configs("plainfold", ALL_URL)
    L.append("### Claude (claude.ai and Claude Desktop)\n")
    L.append(f"Settings → Connectors → **Add custom connector**, paste `{ALL_URL}` and sign in with Apify.\n")
    L.append("Or, in `claude_desktop_config.json`, using [mcp-remote](https://www.npmjs.com/package/mcp-remote) with a token:\n")
    L.append("```json\n" + json.dumps(claude, indent=2) + "\n```\n")
    L.append("### Claude Code\n")
    L.append(f'```bash\nclaude mcp add --transport http plainfold "{ALL_URL}"\n```\n')
    L.append("### Cursor (`~/.cursor/mcp.json`)\n")
    L.append("```json\n" + json.dumps(cursor, indent=2) + "\n```\n(Leave out `headers` to sign in with OAuth instead.)\n")
    L.append("### VS Code (`.vscode/mcp.json`)\n")
    L.append("```json\n" + json.dumps(vscode, indent=2) + "\n```\n")
    L.append("### Any other MCP client\n")
    L.append("Use streamable HTTP with the URL above and the header `Authorization: Bearer YOUR_APIFY_TOKEN`.\n")
    for t in TOOLS:
        L.append(f'## {t["name"]}\n')
        L.append(t["summary"] + "\n")
        L.extend(f"- {d}" for d in t["does"])
        L.append(f'\n**Use it for:** {t["useFor"]}  \n**Not for:** {t["notFor"]}  \n**Price:** {t["price"]}\n')
        L.append(f'- MCP URL: `{mcp_url([t["slug"]])}`\n- MCP tool name: `{tool_name(t)}`\n- Apify page and full docs: {apify_url(t)}\n'
                 f'- Registry entry: [`servers/{t["slug"]}/server.json`](servers/{t["slug"]}/server.json)\n')
        L.append(f'Example prompt: *"{t["examplePrompt"]}"*\n')
        L.append("Example MCP tool call:\n")
        L.append("```json\n" + json.dumps({"name": tool_name(t), "arguments": t["exampleInput"]}, indent=2) + "\n```\n")
        L.append("Or call it over plain HTTP (returns the results as JSON):\n")
        L.append("```bash\ncurl -X POST \"https://api.apify.com/v2/acts/plainfold~" + t["slug"] + "/run-sync-get-dataset-items\" \\\n"
                 "  -H \"Authorization: Bearer $APIFY_TOKEN\" -H \"Content-Type: application/json\" \\\n"
                 f"  -d '{json.dumps(t['exampleInput'])}'\n```\n")
    L.append("## AI agents without an Apify account\n")
    L.append("These tools are eligible for Apify's agentic payments, so an AI agent can run them and pay per use with "
             "[x402](https://docs.apify.com/platform/integrations/x402) or [Skyfire](https://docs.apify.com/platform/integrations/skyfire) instead of an Apify account.\n")
    L.append("## About\n")
    L.append(f'Plainfold is a tiny studio making guides, templates and small tools. Plain on purpose. We use official public data sources, never scrape behind logins, and never return personal data we don\'t need. '
             f'Questions or bugs: [open an issue]({B["repo"]}/issues).\n')
    L.append("This repo holds the docs and the [MCP Registry](https://registry.modelcontextprotocol.io) entries (`server.json`). "
             "The tools themselves run on Apify. Everything here is generated from `tools.json` by `scripts/build.py`.\n")
    L.append("License: MIT (this repo's docs and metadata).\n")
    write(os.path.join(ROOT, "README.md"), "\n".join(L))


def check_site(site):
    """Read-only: compare live status and prices with the website's tools.json. Returns a list of mismatches."""
    path = os.path.join(site, "tools.json")
    if not os.path.exists(path):
        return [f"{path} not found"]
    site_tools = {t["slug"]: t for t in json.load(open(path, encoding="utf-8")).get("tools", [])}
    problems = []
    for t in DATA["tools"]:
        st = site_tools.get(t["slug"])
        if st is None:
            problems.append(f'{t["slug"]}: missing on the site'); continue
        if (st.get("status") == "live") != bool(t.get("live")):
            problems.append(f'{t["slug"]}: live={t.get("live")} here, status={st.get("status")} on the site')
        if t.get("live"):
            here = sorted(float(o["price"]) for o in t.get("priceOffers", []))
            there = sorted(float(p["usd"]) for p in st.get("pricing", []))
            if here != there:
                problems.append(f'{t["slug"]}: prices {here} here vs {there} on the site')
    for slug in site_tools.keys() - {t["slug"] for t in DATA["tools"]}:
        problems.append(f"{slug}: on the site but not in tools.json")
    return problems


if __name__ == "__main__":
    args = sys.argv[1:]
    if args and args[0] != "--check-site":
        sys.exit("build.py no longer writes website files. Use --check-site PATH to compare with the site's tools.json.")
    build_servers()
    readme()
    print("built", [t["slug"] for t in TOOLS])
    if args:
        if len(args) < 2:
            sys.exit("usage: build.py --check-site path/to/site")
        problems = check_site(args[1])
        for p in problems:
            print("MISMATCH", p)
        if problems:
            sys.exit(1)
        print("site tools.json matches: status and prices agree for", len(DATA["tools"]), "tools")
